cacheFolder: /mnt/ddev-global-cache/yarn/sitegeist-neos-base-distribution-web

enableColors: true

enableMessageNames: false

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

progressBarStyle: jack

yarnPath: .yarn/releases/yarn-3.2.1.cjs
