#!/usr/bin/env php
<?php
if (getenv('FLOW_CONTEXT')) {

    /**
     * Bootstrap for the command line
     */

    require(__DIR__ . '/Packages/Framework/Neos.Flow/Scripts/flow.php');

} else {

    /**
     * Bootstrap for docker environment
     */

    $flowArguments = implode(' ', array_slice($argv, 1));

    passthru(sprintf('make -s flow FLOW_ARGS="%s"', $flowArguments));
}
?>
