Sitegeist:
  Monocle:
    hiddenPrototypeNamePatterns:
      - 'Sitegeist.Kaleidoscope:*'

    styleguides:
      'CpxPackage::Vendor.Shared':
        ui:
          grids:
            xs:
              mediaQuery: '(max-width:767px)'
              label: Mobile
              columns: 12
              gap: 16px
              gutter: 0 16px

            md:
              mediaQuery: '(min-width:768px)'
              label: Desktop
              columns: 12
              gap: 32px
              gutter: 0 32px
              maxWidth: 1880px

          viewportPresets:
            md: ~
            xs:
              label: 'Xtra Small'
              width: 320
              height: 768
            s:
              label: 'Small'
              width: 768
              height: 768
            m:
              label: 'Medium'
              width: 1024
              height: 768
            l:
              label: 'Large'
              width: 1280
              height: 768
            xl:
              label: 'Xtra Large'
              width: 1920
              height: 768

          structure:
            layout:
              position: 100
              match: Layout
              label: Layout
              icon: border-all
              color: '#35c3f8'
            ui:
              position: 200
              match: UI
              label: UI
              icon: atom
              color: '#84FAF0'
            block:
              position: 300
              match: Block
              label: Block
              icon: vector-square
              color: '#24F2AD'

        preview:
          styles:
            - 'resource://Vendor.Shared/Public/Build/Styles/main.min.css'
          scripts:
            - 'resource://Vendor.Shared/Public/Build/JavaScript/main.min.js'
